global:
  scrape_interval:     10s
  evaluation_interval: 10s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: twemproxy_exporter
    static_configs:
      - targets: ['twemproxy_exporter:9151']
  - job_name: 'redis_exporter_targets'
    static_configs:
      - targets:
        - redis://redis1:6379
        - redis://redis2:6379
        - redis://redis3:6379
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: redis_exporter:9121
  - job_name: redis_exporter
    static_configs:
      - targets: ['redis_exporter:9121']
  - job_name: docker
    static_configs:
      - targets: ['host.docker.internal:9323']